name: fourth 
 
on: 
  workflow_run: 
    workflows: ["third"]  
    types: 
      - completed   
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: Connect to EC2 and run commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # Your EC2 instance public IP or DNS
          username: sonar  # SSH user for your EC2 instance
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # The SSH private key added as a GitHub secret
          port: 22
          script: |
            cd /opt/sonarqube-10.6.0.92116/bin/linux-x86-64
            ./sonar.sh stop
 
      - name: Call External API
        run: |
          curl -X POST https://ftqp5itzh1.execute-api.ap-south-1.amazonaws.com/default/sonarqube_control \
          -H "Content-Type: application/json" \
          -d '{"control":"stop"}'
