name: fourth 
 
on: 
  workflow_run: 
    workflows: ["third"]  
    types: 
      - completed   
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Call External API 
        run: | 
          curl -X POST https://ftqp5itzh1.execute-api.ap-south-1.amazonaws.com/default/sonarqube_control  \ 
          -H "Content-Type: application/json" \ 
          -d '{ "control":"stop"}' 
