name: API Request and Print Total

on:
  push:
    branches:
      - main

jobs:
  api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API Request
        id: api_request
        run: |
          total=0
          attempts=0
          max_attempts=5

          while [ "$total" -lt 1 ] && [ "$attempts" -lt "$max_attempts" ]; do
            # Make the API request and capture the response and HTTP status code
            response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer sqp_caf7305c1c9c8d5b3f4f0e34b91bd5d4c3f82710" "http://13.201.109.77:9000/api/issues/search?componentKeys=test&types=BUG,VULNERABILITY,CODE_SMELL")
            http_code="${response: -3}"  # Extract the last 3 characters as the HTTP status code
            body="${response:0:${#response}-3}"  # Extract the body

            if [ "$http_code" -ne 200 ]; then
              echo "Failed to reach server, HTTP status code: $http_code. Marking total as 0."
              total=0
            else
              echo "Response: $body"
              total=$(echo "$body" | jq '.total')
            fi

            echo "Total: $total"
            attempts=$((attempts + 1))

            if [ "$total" -lt 1 ]; then
              echo "Total is less than 1 or no valid response. Retrying... ($attempts/$max_attempts)"
              sleep 2  # Optional: wait for a few seconds before retrying
            fi
          done

          if [ "$total" -lt 1 ]; then
            echo "Failed to retrieve a total of 1 or more after $max_attempts attempts."
          else
            echo "Successfully retrieved total: $total"
          fi
