name: third

on:
  workflow_run:
    workflows: ["second"] 
    types:
      - completed  


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for better SonarQube analysis

      - name: Wait for 20 seconds
        run: sleep 20

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=demo \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://${{ secrets.EC2_PUBLIC_IP }}:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait for 20 seconds
        run: sleep 20    
          
      - name: Fetch Full List of Issues from SonarQube
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "http://${{ secrets.EC2_PUBLIC_IP }}:9000/api/issues/search?componentKeys=demo&types=BUG,VULNERABILITY,CODE_SMELL" \
          -o sonarqube_issues.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Prettify JSON Report
        run: |
          cat sonarqube_issues.json | jq '.' > sonarqube-report.json

      - name: Upload Pretty Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube-report
          path: sonarqube-report.json    
          
      - name: Send email on success or failure
        if: always()  # ensures that this step runs no matter what
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}      # app password from google account
          subject: "GitHub Action Pipeline Status - ${{ job.status }}"
          body: |
            The GitHub Action for your project has completed.
          
            Status: ${{ job.status }} 
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}

            Check the details at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          secure: true
          attachments: sonarqube-report.json
