name: third

on:
  workflow_run:
    workflows: ["second"] 
    types:
      - completed  


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for better SonarQube analysis

      - name: Wait for 30 seconds
        run: sleep 30


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=demo \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://${{ secrets.EC2_PUBLIC_IP }}:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Fetch Full List of Issues from SonarQube
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "http://${{ secrets.EC2_PUBLIC_IP }}:9000/api/issues/search?componentKeys=demo&types=BUG,VULNERABILITY,CODE_SMELL" \
          -o sonarqube_issues.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
      - name: Fetch Project Metrics Report from SonarQube
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "http://${{ secrets.EC2_PUBLIC_IP }}:9000/api/measures/component?component=demo&metricKeys=coverage,bugs,vulnerabilities,code_smells,duplicated_lines_density" \
          -o sonarqube_metrics.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload Issues Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube-issues
          path: sonarqube_issues.json

      - name: Upload Metrics Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube-metrics
          path: sonarqube_metrics.json
